import polars as pl

def compute_xpha_only(df: pl.DataFrame, freq_list, site: str = 'TIR') -> tuple[pl.DataFrame, pl.DataFrame]: ...
def compute_xpha_full(df: pl.DataFrame, freq_list, site: str = 'TIR'): ...
def compute_kvector(df: pl.DataFrame, freq_list, sort_by_freq: bool = False, points_thres: int = 5, site: str = 'TIR'): ...
def compute_vel(df: pl.DataFrame, freq_list, points_thres: int = 5, site: str = 'TIR'): ...
def compute_xy(df: pl.DataFrame, freq_list, sort_by_freq: bool = False, points_thres: int = 5, site: str = 'TIR'): ...
