import _cython_3_3_0
import dataclasses
import functools
from typing import Callable, ClassVar

DEFAULT_SITES: dict
__test__: dict
get_sites_json_path: _cython_3_3_0.cython_function_or_method
load_sites_file: functools._lru_cache_wrapper

class SiteInfo:
    """SiteInfo(FH: 'float', dip: 'float', site: 'str', short_site: 'str', ph_corr: 'List[float]', polarity: 'List[float]', site_separation: 'List[float]')"""
    __init__: ClassVar[Callable] = ...
    from_file: ClassVar[method] = ...
    get_from_file: ClassVar[method] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __eq__: ClassVar[Callable] = ...
    __match_args__: ClassVar[tuple] = ...
    __replace__: ClassVar[Callable] = ...
    def get_tzinfo(self, *args, **kwargs): ...
    def get_tzstr(self, *args, **kwargs): ...
