import _abc
import abc
import dataclasses
from typing import Callable, ClassVar

__test__: dict

class BaseOutput(abc.ABC):
    """BaseOutput()"""
    __init__: ClassVar[Callable] = ...
    _abc_impl: ClassVar[_abc._abc_data] = ...
    __abstractmethods__: ClassVar[frozenset] = ...
    __annotate_func__: ClassVar[None] = ...
    __annotations_cache__: ClassVar[dict] = ...
    __dataclass_fields__: ClassVar[dict] = ...
    __dataclass_params__: ClassVar[dataclasses._DataclassParams] = ...
    __eq__: ClassVar[Callable] = ...
    __match_args__: ClassVar[tuple] = ...
    __replace__: ClassVar[Callable] = ...
